### PR TITLE
Refactored to use more modern tools (shell-conduit, stack)

### PR DESCRIPTION
**Pull request by yihuang**

### CODE REVIEW

**Comment by grwlf** [comment]
Hi, yihuang 
Thank you very much for the refactoring. I've accepted the changes in GitHub, but I'd like to delay Hackage update until we add fallback-option for bare ghc-pkg. This is important for me, because I run NixOS which is in some way a competitor of Stack. It uses its own Haskell package manager which is aware of stack package sets (lts-*) but doesn't use stack binary.

I plan to employ the shining Optparse.Applicative for arguments parsing, add  --stack/--ghc-pkg flags with --stack set by default and after that publish the package.

**Comment by yihuang** [comment]
I just find codex, which seems to do excactly what haskdogs does. Just mention it to you.


    _____________________________

**Comment by grwlf** [comment]
THanks, didn't know about codex. Looks huge. From the other side, it offers full dependencies list. I'll try it in action

**Comment by grwlf** [comment]
There are more of them http://hackage.haskell.org/package/hothasktags !

**Comment by grwlf** [comment]
yihuang, I've updated the code to handle both cabal and stack-based setups. Could you please check the stack branch? Note, I'm using new home repository located at https://github.com/grwlf/haskdogs

**Comment by yihuang** [comment]
It still works for me.

Sent from Outlook




On Wed, Nov 18, 2015 at 12:50 PM -0800, "Sergey Mironov" <notifications@github.com> wrote:












yihuang, I've updated the code to handle both cabal and stack-based setups. Could you please check the stack branch? Note, I'm using new home repository located at https://github.com/grwlf/haskdogs

**Pull request merged**
